// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareOutputs(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompareOutputs'](arg1, arg2, arg3);
}

export function GetActualOutput(arg1, arg2) {
  return window['go']['main']['App']['GetActualOutput'](arg1, arg2);
}

export function GetAllFiles() {
  return window['go']['main']['App']['GetAllFiles']();
}

export function GetAllTestcaseIds(arg1) {
  return window['go']['main']['App']['GetAllTestcaseIds'](arg1);
}

export function GetAllTestcases(arg1) {
  return window['go']['main']['App']['GetAllTestcases'](arg1);
}

export function GetDiff(arg1, arg2) {
  return window['go']['main']['App']['GetDiff'](arg1, arg2);
}

export function GetDiffChangedEvent() {
  return window['go']['main']['App']['GetDiffChangedEvent']();
}

export function GetExpectedOutput(arg1, arg2) {
  return window['go']['main']['App']['GetExpectedOutput'](arg1, arg2);
}

export function GetInput(arg1, arg2) {
  return window['go']['main']['App']['GetInput'](arg1, arg2);
}

export function GetOutputChangedEvent() {
  return window['go']['main']['App']['GetOutputChangedEvent']();
}

export function OnFileSelected(arg1) {
  return window['go']['main']['App']['OnFileSelected'](arg1);
}

export function OnTestcaseChanged(arg1, arg2) {
  return window['go']['main']['App']['OnTestcaseChanged'](arg1, arg2);
}

export function OnTestcaseDeleted(arg1, arg2) {
  return window['go']['main']['App']['OnTestcaseDeleted'](arg1, arg2);
}

export function ProcessSolution(arg1) {
  return window['go']['main']['App']['ProcessSolution'](arg1);
}

export function RunCode(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunCode'](arg1, arg2, arg3, arg4, arg5);
}
