// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetAllSolutionFiles():Promise<Array<string>>;

export function GetAllTestcaseIds(arg1:string):Promise<Array<string>>;

export function GetAllTestcases(arg1:string):Promise<Array<model.Testcase>>;

export function GetCurrentPath():Promise<string>;

export function GetLanguages():Promise<Array<model.Language>>;

export function GetTestcase(arg1:string,arg2:string):Promise<model.Testcase>;

export function GetTestcaseRuns(arg1:string):Promise<Array<model.TestcaseRun>>;

export function RunCode(arg1:string,arg2:string):Promise<boolean>;

export function SaveTestcases(arg1:string,arg2:Array<model.Testcase>):Promise<void>;

export function SelectFile(arg1:string):Promise<model.File>;
