// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CompareOutputs(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActualOutput(arg1:model.File,arg2:string):Promise<string>;

export function GetAllFiles():Promise<Array<model.File>>;

export function GetAllTestcaseIds(arg1:model.File):Promise<Array<string>>;

export function GetAllTestcases(arg1:model.File):Promise<Array<model.Testcase>>;

export function GetDiff(arg1:model.File,arg2:string):Promise<string>;

export function GetDiffChangedEvent():Promise<model.DiffChangedEvent>;

export function GetExpectedOutput(arg1:model.File,arg2:string):Promise<string>;

export function GetInput(arg1:model.File,arg2:string):Promise<string>;

export function GetOutputChangedEvent():Promise<model.OutputChangedEvent>;

export function OnFileSelected(arg1:model.File):Promise<void>;

export function OnTestcaseChanged(arg1:model.File,arg2:model.Testcase):Promise<void>;

export function OnTestcaseDeleted(arg1:model.File,arg2:string):Promise<void>;

export function ProcessSolution(arg1:model.File):Promise<void>;

export function RunCode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:model.Language):Promise<boolean>;
