// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllSolutionFiles() {
  return window['go']['main']['App']['GetAllSolutionFiles']();
}

export function GetAllTestcaseIds(arg1) {
  return window['go']['main']['App']['GetAllTestcaseIds'](arg1);
}

export function GetAllTestcases(arg1) {
  return window['go']['main']['App']['GetAllTestcases'](arg1);
}

export function GetCurrentPath() {
  return window['go']['main']['App']['GetCurrentPath']();
}

export function GetLanguages() {
  return window['go']['main']['App']['GetLanguages']();
}

export function GetTestcase(arg1, arg2) {
  return window['go']['main']['App']['GetTestcase'](arg1, arg2);
}

export function GetTestcaseRuns(arg1) {
  return window['go']['main']['App']['GetTestcaseRuns'](arg1);
}

export function RunCode(arg1, arg2) {
  return window['go']['main']['App']['RunCode'](arg1, arg2);
}

export function SaveTestcases(arg1, arg2) {
  return window['go']['main']['App']['SaveTestcases'](arg1, arg2);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
